In [1]:
import sys
import os

# Get the parent directory of the current folder
project_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_dir not in sys.path:
    sys.path.insert(0, project_dir)


In [2]:
import numpy as np
import plotly.graph_objects as go
from scipy.optimize import minimize
from tqdm import tqdm
from scipy.stats import t, multivariate_normal, multivariate_t
from scipy.special import logsumexp, gamma, gammaln
from numpy.linalg import inv, det, slogdet, LinAlgError
import plotly.express as px
from plotly.subplots import make_subplots
from numpy import tril_indices, triu_indices
from typing import Literal, Optional, Dict, Union

# from simulation import * 

from Functions.simulation_1 import * 
# from Functions.gas_filter_2 import *
# from Functions.kf_filter_2 import *
from Functions.gas_filter_5 import *
from Functions.kf_filter_5 import *

## $\Phi$ Full, $Q, R$ Full

In [ ]:
T = 1000
N = 3
K = 2

c_true_3x3 = np.array([0.2, -0.1, 0.4])

Phi_true_3x3_phi_full_yes_noise_correl = np.array([[0.8, 0.2, 0.1],
                                                    [0.1, 0.7, 0.2],
                                                    [0.1, 0.1, 0.6]])

beta_true_3x3 = np.array([[1.0, -0.5, 0.2],
                          [-1.2, 0.8, 0.4],])

Q_true_3x3_yes_correl = np.array([[0.5, 0.2, 0.3],
                                 [0.2, 0.6, 0.1],
                                 [0.3, 0.1, 0.5]])

R_true_3x3_yes_correl = np.array([[0.4, 0.1, 0.2],
                                 [0.1, 0.5, 0.3],
                                 [0.2, 0.3, 0.5]])


y_sim_3x3_phi_full_yes_noise_correl, mu_sim_3x3_phi_full_yes_noise_correl, X_sim_3x3_phi_full_yes_noise_correl = simulate_multivariate_state_space(
    T=T,
    N=N,
    c=c_true_3x3,
    Phi=Phi_true_3x3_phi_full_yes_noise_correl,
    beta=beta_true_3x3, 
    Q=Q_true_3x3_yes_correl,
    R=R_true_3x3_yes_correl,
    # use_intercept=None,
    seed=8888,
    t_noise=True,
    nu= 10
)

In [ ]:
initial_params_3x3_phi_full_yes_noise_correl = np.concatenate([
    c_true_3x3, 
    Phi_true_3x3_phi_full_yes_noise_correl.flatten(), 
    beta_true_3x3.flatten(), 
    np.ones(N * (N + 1) // 2),  # L_Q_elements
    np.ones(N * (N + 1) // 2)   # L_R_elements
])

kf_results_3x3_phi_full_yes_correl  =  multivariate_KF_with_estimation(
    y=y_sim_3x3_phi_full_yes_noise_correl,
    X=X_sim_3x3_phi_full_yes_noise_correl,
    verbose=True,
    ftol=1e-8,
    gtol=1e-5,
)

mu_kf_3x3_phi_full_yes_correl = kf_results_3x3_phi_full_yes_correl['mu_filtered']
P_kf_3x3_phi_full_yes_correl = kf_results_3x3_phi_full_yes_correl['P_filtered']
kalman_gain_kf_3x3_phi_full_yes_correl = kf_results_3x3_phi_full_yes_correl['kalman_gain']

✅ Kalman estimation completed successfully.
Estimated parameters:
omega (unconditional mean): [-0.21962191  0.07801968  0.5600662 ]
Phi (persistence matrix): 
[[1.21269271 0.19196091 0.32162265]
 [0.21131488 0.94964043 0.33629516]
 [0.17783124 0.09805771 0.94324712]]
beta: 
[[ 1.80068477 -0.52184687  0.51198736]
 [-1.15895837  0.85023166  0.44013485]]
Q (state noise covariance): 
[[0.41997243 0.27249573 0.14052342]
 [0.27249573 0.76158504 0.09194241]
 [0.14052342 0.09194241 0.42163175]]
R (observation noise covariance): 
[[0.60445351 0.1123162  0.40957749]
 [0.1123162  0.51185886 0.3889131 ]
 [0.40957749 0.3889131  0.68847697]]
Log-likelihood: -4395.720300721743
AIC: 8851.440601443486
BIC: 9031.631628472993


In [6]:
gas_results_3x3_phi_full_yes_correl_1 = estimate_and_filter_gas(
                                        y=y_sim_3x3_phi_full_yes_noise_correl, 
                                        X=X_sim_3x3_phi_full_yes_noise_correl, 
                                        phi_type= "full", 
                                        kappa_type= "full", 
                                        fix_nu=10,
                                        ftol = 1e-8,  # Tolerance for convergence
                                        gtol = 1e-5,   # Gradient tolerance for convergence)
)


mu_gas_3x3_phi_full_yes_correl_1 = gas_results_3x3_phi_full_yes_correl_1["mu_filtered"]
u_gas_3x3_phi_full_yes_correl_1 = gas_results_3x3_phi_full_yes_correl_1["u"]
resid_gas_phi_full_yes_correl_1 = gas_results_3x3_phi_full_yes_correl_1["resid"]
Kappa_est_3x3_phi_full_yes_correl_1 = gas_results_3x3_phi_full_yes_correl_1["Kappa"]

Estimated omega:
 [0.3073665 0.2718786 0.1347773]
Estimated Phi:
 [[ 0.76372905  0.13162454  0.27391297]
 [-0.01088989  0.73996238  0.3643341 ]
 [ 0.047021    0.14309001  0.63029218]]
Estimated beta:
 [[ 9.79696355  5.02515892  4.76972602]
 [-1.1481457   0.83701968  0.44222644]]
Estimated Omega (from lambda):
 [[1.1503056  0.         0.        ]
 [0.         1.23033118 0.        ]
 [0.         0.         1.07092265]]
Estimated Kappa:
 [[ 0.80351259  0.40128497 -0.0714741 ]
 [ 0.35565399  0.77303523 -0.1377822 ]
 [ 0.21016085  0.06097447  0.39845867]]
Estimated nu:
 10
Log-likelihood: -4707.426607230362
AIC: 9474.853214460723
BIC: 9655.04424149023


In [ ]:
phi_type = "full"
kappa_type = "full"
X_shared = True
fix_nu = 10
R = N
P = X_sim_3x3_phi_full_yes_noise_correl.shape[1]


lambda_true = 0.5 * np.log(np.diag(R_true_3x3_yes_correl))  # diagonal Lambda

# For Kappa set to identity or try a scaled value
Kappa_true = np.eye(N) 
kappa_true_flat = Kappa_true.flatten()

# Compose params vector
params_true = np.concatenate([
    Phi_true_3x3_phi_full_yes_noise_correl.flatten(),
    # omega, use the true unconditional mean
    np.linalg.solve(np.eye(N) - Phi_true_3x3_phi_full_yes_noise_correl, c_true_3x3),
    beta_true_3x3.flatten(),
    lambda_true,
    kappa_true_flat,
    [fix_nu]
])

# Get param sizes for slicing
cL = N
cK = N * N  # "full"
# Evaluate loglikelihood at true parameters
neg_loglik_true = gas_general_filter(
    params_true, y_sim_3x3_phi_full_yes_noise_correl, X_sim_3x3_phi_full_yes_noise_correl,
    cL, cK, fix_nu=fix_nu, kappa_type=kappa_type, phi_type=phi_type, X_shared=X_shared
)
print("GAS loglik at true params:", -neg_loglik_true)



GAS loglik at true params: -6091.212836146152


In [8]:
import numpy as np
from scipy.stats import t, norm

from scipy.stats import multivariate_t, multivariate_normal

from scipy.stats import multivariate_normal

loglik_t = 0
loglik_norm = 0

for t in range(T):
    obs = y_sim_3x3_phi_full_yes_noise_correl[t]
    mu = mu_sim_3x3_phi_full_yes_noise_correl[t] + X_sim_3x3_phi_full_yes_noise_correl[t] @ beta_true_3x3
    Omega = R_true_3x3_yes_correl
    nu = 10

    loglik_t += multivariate_t.logpdf(obs, loc=mu, shape=Omega, df=nu)
    loglik_norm += multivariate_normal.logpdf(obs, mean=mu, cov=Omega)

print("Sum log-likelihood t(10):", loglik_t)
print("Sum log-likelihood Gaussian:", loglik_norm)



Sum log-likelihood t(10): -3099.0737055493723
Sum log-likelihood Gaussian: -3133.036220116899


In [10]:
gas_specs = [
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": None, "label": "GAS_diag_diag_nufree"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 5, "label": "GAS_diag_diag_nu10"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 10, "label": "GAS_diag_diag_nu10"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 20, "label": "GAS_diag_diag_nu20"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 50, "label": "GAS_diag_diag_nu50"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 100, "label": "GAS_diag_diag_nu100"},
    {"phi_type": "diagonal", "kappa_type": "diagonal", "fix_nu": 500, "label": "GAS_diag_diag_nu500"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": None, "label": "GAS_diag_full_nufree"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 5, "label": "GAS_diag_full_nu5"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 10, "label": "GAS_diag_full_nu10"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 20, "label": "GAS_diag_full_nu20"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 50, "label": "GAS_diag_full_nu50"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 100, "label": "GAS_diag_full_nu100"},
    {"phi_type": "diagonal", "kappa_type": "full", "fix_nu": 500, "label": "GAS_diag_full_nu500"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": None, "label": "GAS_full_diag_nufree"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 5, "label": "GAS_full_diag_nu5"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 10, "label": "GAS_full_diag_nu10"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 20, "label": "GAS_full_diag_nu20"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 50, "label": "GAS_full_diag_nu50"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 100, "label": "GAS_full_diag_nu100"},
    {"phi_type": "full", "kappa_type": "diagonal", "fix_nu": 500, "label": "GAS_full_diag_nu500"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": None, "label": "GAS_full_full_nufree"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 5, "label": "GAS_full_full_nu5"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 10, "label": "GAS_full_full_nu10"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 20, "label": "GAS_full_full_nu20"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 50, "label": "GAS_full_full_nu50"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 100, "label": "GAS_full_full_nu100"},
    {"phi_type": "full", "kappa_type": "full", "fix_nu": 500, "label": "GAS_full_full_nu500"},
    # Add more specs as needed
]

In [ ]:
from collections import defaultdict

spec_results = defaultdict(list)
target_success = 30
sim_counter = 0

while any(len(v) < target_success for v in spec_results.values()) or len(spec_results) == 0:
    sim_seed = 8888 + sim_counter
    sim_counter += 1
    # Simulate data
    y_sim, mu_sim, X_sim = simulate_multivariate_state_space(
            T=T,
            N=N,
            c=c_true_3x3,
            Phi=Phi_true_3x3_phi_full_yes_noise_correl,
            beta=beta_true_3x3, 
            Q=Q_true_3x3_yes_correl,
            R=R_true_3x3_yes_correl,
            seed=sim_seed,
        )
    # KF
    try:
        if len(spec_results["KF"]) < target_success:
            kf_results = multivariate_KF_with_estimation(
            y=y_sim, 
            X=X_sim, 
            initial_params=None, 
            verbose=False,
            ftol=1e-8,  # Tolerance for convergence
            gtol=1e-5,  # Gradient tolerance for convergence,
        )
            # Calculate MSE for mu
            mu_kf = kf_results['mu_filtered']
            mse_kf = np.mean((mu_sim[1:] - mu_kf[1:]) ** 2)
            mae_kf = np.mean(np.abs(mu_sim[1:] - mu_kf[1:]))

            spec_results["KF"].append({
                "seed": sim_seed, "loglik": kf_results["loglik"],
                "aic": kf_results["aic"], "bic": kf_results["bic"],
                "mse": mse_kf, "mae": mae_kf
                })

    except Exception as e:
        print(f"KF failed: {e}")
    # GAS
    for spec in gas_specs:
        try:
            label = spec["label"]
            if len(spec_results[label]) < target_success:
                res_gas = estimate_and_filter_gas(
                    y=y_sim, 
                    X=X_sim,
                    phi_type=spec["phi_type"], 
                    kappa_type=spec["kappa_type"],
                    fix_nu=spec["fix_nu"], 
                    verbose=False,
                    ftol=1e-8,  # Tolerance for convergence
                    gtol=1e-5   # Gradient tolerance for convergence
                )

                # Calculate MSE for mu
                mu_gas = res_gas["mu_filtered"]
                mse_gas = np.mean((mu_sim[1:] - mu_gas[1:]) ** 2)
                mae_gas = np.mean(np.abs(mu_sim[1:] - mu_gas[1:]))

                spec_results[label].append({
                    "seed": sim_seed, "loglik": res_gas["loglik"],
                    "aic": res_gas["aic"], "bic": res_gas["bic"],
                    "mse": mse_gas, "mae": mae_gas
                })
        except Exception as e:
            print(f"GAS {label} failed: {e}")

    # Break if all filled
    if all(len(v) >= target_success for v in spec_results.values()):
        break



c:\Users\vliu_sym\Desktop\Thesis\Python Implementation\Functions\gas_filter_2.py:190: RuntimeWarning: invalid value encountered in matmul
  mu[t + 1] = omega + Phi @ (mu[t] - omega) + Kappa @ u_t
c:\Users\vliu_sym\Desktop\Thesis\Python Implementation\Functions\gas_filter_2.py:19: RuntimeWarning: overflow encountered in matmul
  eps = inv_sqrt_Omega @ diff
c:\Users\vliu_sym\Desktop\Thesis\Python Implementation\Functions\gas_filter_2.py:189: RuntimeWarning: overflow encountered in matmul
  u_t = (Lambda_inv @ resid) / alpha_t
c:\Users\vliu_sym\Desktop\Thesis\Python Implementation\Functions\gas_filter_2.py:189: RuntimeWarning: invalid value encountered in divide
  u_t = (Lambda_inv @ resid) / alpha_t


In [ ]:
test1 = mu_sim[1:]
test2 = kf_results['mu_filtered'][1:]
test3 = res_gas["mu_filtered"][1:]

In [ ]:
np.mean((test1 - test2)**2)  # Should be close to zero if KF is working correctly

np.float64(1.6254717377848062)

In [ ]:
np.mean((test1 - test3)**2)  # Should be close to zero if GAS is working correctly

np.float64(1.5388307135189712)

In [ ]:
import pandas as pd

# Flatten to long-form list of dicts
rows = []
for spec_label, run_list in spec_results.items():
    for run in run_list:
        row = {'spec': spec_label}
        row.update(run)  # adds 'seed', 'loglik', etc.
        rows.append(row)

df_results = pd.DataFrame(rows)


agg = df_results.groupby('spec').agg({
    'loglik': ['mean', 'std'],
    'aic': ['mean', 'std'],
    'bic': ['mean', 'std'],
    'mse': ['mean', 'std'],  # Mean Squared Error
    'mae': ['mean', 'std'],  # Mean Absolute Error
    # add more metrics here if you wish!
}).reset_index()
# Flatten MultiIndex columns
agg.columns = ['spec', 'loglik_mean', 'loglik_std', 'aic_mean', 'aic_std', 'bic_mean', 'bic_std', 'mse_mean', 'mse_std', 'mae_mean', 'mae_std']  # Added mse and mae


agg

spec  loglik_mean   loglik_std      aic_mean      aic_std  \
0     GAS_diag_diag_nu10 -4707.901817    48.415570   9457.803633    96.831141   
1    GAS_diag_diag_nu100 -4617.332526    38.373631   9276.665053    76.747263   
2     GAS_diag_diag_nu20 -4626.805535    39.305689   9295.611070    78.611377   
3     GAS_diag_diag_nu50 -4617.820603    38.629638   9277.641206    77.259277   
4    GAS_diag_diag_nu500 -4618.393999    38.143195   9278.787997    76.286389   
5   GAS_diag_diag_nufree -4672.565258   258.111023   9389.130516   516.222046   
6     GAS_diag_full_nu10 -4600.133400    40.097544   9254.266801    80.195089   
7    GAS_diag_full_nu100 -5007.922384  1915.256245  10069.844768  3830.512491   
8     GAS_diag_full_nu20 -4580.262302    38.223591   9214.524604    76.447183   
9      GAS_diag_full_nu5 -4656.360684    43.412250   9366.721369    86.824499   
10    GAS_diag_full_nu50 -4990.635057  1850.818020  10035.270113  3701.636040   
11   GAS_diag_full_nu500 -4580.957699    36.616070   9215.915397    73.232141   
12  GAS_diag_full_nufree -4573.610624    38.337251   9203.221248    76.674502   
13    GAS_full_diag_nu10 -4583.115565    49.381230   9220.231130    98.762459   
14   GAS_full_diag_nu100 -4551.561214    45.775958   9157.122428    91.551916   
15    GAS_full_diag_nu20 -4558.753252    47.366120   9171.506503    94.732241   
16     GAS_full_diag_nu5 -4648.514654    52.923406   9351.029308   105.846812   
17    GAS_full_diag_nu50 -4551.545959    46.167549   9157.091917    92.335098   
18   GAS_full_diag_nu500 -4552.992466    45.451299   9159.984931    90.902598   
19  GAS_full_diag_nufree -4550.985537    46.171595   9157.971074    92.343190   
20    GAS_full_full_nu10 -4537.245393    45.593540   9140.490785    91.187079   
21   GAS_full_full_nu100 -4518.542782    42.177665   9103.085563    84.355331   
22    GAS_full_full_nu20 -4519.109412    43.609320   9104.218825    87.218641   
23     GAS_full_full_nu5 -4593.217354    48.927832   9252.434707    97.855665   
24    GAS_full_full_nu50 -4516.645674    42.512338   9099.291348    85.024676   
25   GAS_full_full_nu500 -4521.641665    41.908746   9109.283330    83.817492   
26  GAS_full_full_nufree -4515.813509    43.183225   9099.627018    86.366449   
27                    KF -4223.538038    29.745206   8513.076076    59.490411   

        bic_mean      bic_std   mse_mean    mse_std  mae_mean   mae_std  
0    9583.937352    96.831141   2.974620   0.667126  1.580174  0.206886  
1    9402.798772    76.747263   2.931520   0.574299  1.587475  0.177175  
2    9421.744788    78.611377   2.994767   0.637997  1.603761  0.196187  
3    9403.774925    77.259277   3.039385   0.616888  1.619082  0.191238  
4    9404.921716    76.286389   2.950629   0.604243  1.592704  0.186018  
5    9521.270602   516.222046  14.758167   5.768076  3.514552  0.828665  
6    9416.438725    80.195089   3.318673   2.117491  1.612423  0.346314  
7   10232.016692  3830.512491   7.359005  19.304271  1.975778  1.714842  
8    9376.696528    76.447183   3.077168   0.811647  1.611318  0.238341  
9    9528.893293    86.824499   2.948650   0.612117  1.558586  0.190687  
10  10197.442037  3701.636040   7.809940  19.141364  2.062386  1.737353  
11   9378.087321    73.232141   3.459278   2.574501  1.647757  0.439986  
12   9371.399540    76.674502  11.915054   3.866186  2.887390  0.563378  
13   9382.403055    98.762459   2.719049   0.546332  1.508788  0.175586  
14   9319.294352    91.551916   2.677555   0.531198  1.504266  0.169181  
15   9333.678427    94.732241   2.678380   0.514786  1.501214  0.164620  
16   9513.201233   105.846812   2.829954   0.742565  1.525692  0.223669  
17   9319.263842    92.335098   2.667162   0.511336  1.500291  0.162497  
18   9322.156856    90.902598   2.670223   0.520582  1.502231  0.162634  
19   9326.149366    92.343190  11.274638   3.375343  2.766587  0.449530  
20   9338.700915    91.187079   2.675306   0.507185  1.495565  0.162995  
21   9301.295693    84.355331   2.644158  

In [11]:
from collections import defaultdict

spec_results = defaultdict(list)
target_success = 30
sim_counter = 0

while any(len(v) < target_success for v in spec_results.values()) or len(spec_results) == 0:
    sim_seed = 8888 + sim_counter
    sim_counter += 1
    # Simulate data
    # Run explicit simulation with regressors
    y_sim, mu_sim, X_sim = simulate_multivariate_state_space(
            T=T,
            N=N,
            c=c_true_3x3,
            Phi=Phi_true_3x3_phi_full_yes_noise_correl,
            beta=beta_true_3x3,  # Explicitly include regressors
            Q=Q_true_3x3_yes_correl,
            R=R_true_3x3_yes_correl,
            # use_intercept=None,
            seed=sim_seed,
        )
    # KF
    try:
        if len(spec_results["KF"]) < target_success:
            kf_results = multivariate_KF_with_estimation(
            y=y_sim, 
            X=X_sim, 
            initial_params=None, 
            verbose=False,
            ftol=1e-8,  # Tolerance for convergence
            gtol=1e-5,  # Gradient tolerance for convergence,
        )
            # Calculate MSE for mu
            mu_kf = kf_results['mu_filtered']
            mse_kf = np.mean((mu_sim[1:] - mu_kf[1:]) ** 2)
            mae_kf = np.mean(np.abs(mu_sim[1:] - mu_kf[1:]))

            spec_results["KF"].append({
                "seed": sim_seed, "loglik": kf_results["loglik"],
                "aic": kf_results["aic"], "bic": kf_results["bic"],
                "mse": mse_kf, "mae": mae_kf
                })

    except Exception as e:
        print(f"KF failed: {e}")
    # GAS
    for spec in gas_specs:
        try:
            label = spec["label"]
            if len(spec_results[label]) < target_success:
                res_gas = estimate_and_filter_gas(
                    y=y_sim, 
                    X=X_sim,
                    phi_type=spec["phi_type"], 
                    kappa_type=spec["kappa_type"],
                    fix_nu=spec["fix_nu"], 
                    verbose=False,
                    ftol=1e-8,  # Tolerance for convergence
                    gtol=1e-5   # Gradient tolerance for convergence
                )

                # Calculate MSE for mu
                mu_gas = res_gas["mu_filtered"]
                mse_gas = np.mean((mu_sim[1:] - mu_gas[1:]) ** 2)
                mae_gas = np.mean(np.abs(mu_sim[1:] - mu_gas[1:]))

                spec_results[label].append({
                    "seed": sim_seed, "loglik": res_gas["loglik"],
                    "aic": res_gas["aic"], "bic": res_gas["bic"],
                    "mse": mse_gas, "mae": mae_gas
                })
        except Exception as e:
            print(f"GAS {label} failed: {e}")

    # Break if all filled
    if all(len(v) >= target_success for v in spec_results.values()):
        break

# Now you can flatten/aggregate spec_results as needed


GAS GAS_full_full_nu5 failed: Estimation failed: ABNORMAL: 
GAS GAS_full_full_nufree failed: Estimation failed: ABNORMAL: 


In [ ]:
import pandas as pd

rows = []
for spec_label, run_list in spec_results.items():
    for run in run_list:
        row = {'spec': spec_label}
        row.update(run)  
        rows.append(row)

df_results = pd.DataFrame(rows)


agg = df_results.groupby('spec').agg({
    'loglik': ['mean', 'std'],
    'aic': ['mean', 'std'],
    'bic': ['mean', 'std'],
    'mse': ['mean', 'std'], 
    'mae': ['mean', 'std'],  

}).reset_index()

agg.columns = ['spec', 'loglik_mean', 'loglik_std', 'aic_mean', 'aic_std', 'bic_mean', 'bic_std', 'mse_mean', 'mse_std', 'mae_mean', 'mae_std']  


agg

spec  loglik_mean  loglik_std     aic_mean      aic_std  \
0     GAS_diag_diag_nu10 -4669.367862   67.106145  9374.735723   134.212289   
1    GAS_diag_diag_nu100 -4586.852037   46.319291  9209.704074    92.638583   
2     GAS_diag_diag_nu20 -4595.887268   48.580894  9227.774536    97.161787   
3     GAS_diag_diag_nu50 -4587.328071   47.014866  9210.656142    94.029731   
4    GAS_diag_diag_nu500 -4587.826413   45.673036  9211.652826    91.346072   
5   GAS_diag_diag_nufree -4586.433202   46.728030  9210.866403    93.456059   
6     GAS_diag_full_nu10 -4552.163564   51.550694  9152.327128   103.101388   
7    GAS_diag_full_nu100 -4622.080830  291.203420  9292.161660   582.406840   
8     GAS_diag_full_nu20 -4534.154464   49.484881  9116.308928    98.969762   
9      GAS_diag_full_nu5 -4608.285976   53.878506  9264.571952   107.757011   
10    GAS_diag_full_nu50 -4600.978484  365.828830  9249.956969   731.657661   
11   GAS_diag_full_nu500 -4547.324848   46.376713  9142.649697    92.753427   
12  GAS_diag_full_nufree -4533.118114   47.895604  9116.236228    95.791208   
13    GAS_full_diag_nu10 -4560.336309   49.443492  9168.672619    98.886985   
14   GAS_full_diag_nu100 -4527.290367   45.447854  9102.580733    90.895708   
15    GAS_full_diag_nu20 -4535.126464   47.529473  9118.252928    95.058946   
16     GAS_full_diag_nu5 -4626.336340   51.700469  9300.672681   103.400938   
17    GAS_full_diag_nu50 -4527.317883   46.029379  9102.635767    92.058758   
18   GAS_full_diag_nu500 -4528.389672   44.871003  9104.779344    89.742005   
19  GAS_full_diag_nufree -4526.127575   45.710961  9102.255150    91.421921   
20    GAS_full_full_nu10 -4496.852386   50.915684  9053.704772   101.831369   
21   GAS_full_full_nu100 -4482.460857   46.211060  9024.921715    92.422121   
22    GAS_full_full_nu20 -4480.287243   49.041908  9020.574486    98.083816   
23     GAS_full_full_nu5 -4550.562427   52.951556  9161.124854   105.903112   
24    GAS_full_full_nu50 -4480.052818   48.864968  9020.105636    97.729936   
25   GAS_full_full_nu500 -4484.132683   46.355717  9028.265367    92.711434   
26  GAS_full_full_nufree -4584.556600  563.361511  9231.113201  1126.723022   
27                    KF -4194.760519   37.961688  8449.521038    75.923376   

       bic_mean      bic_std    mse_mean      mse_std   mae_mean    mae_std  
0   9482.850339   134.212289   50.562349     9.530761   6.770236   0.678906  
1   9317.818690    92.638583   38.151358    10.286445   5.872994   0.813192  
2   9335.889152    97.161787   48.856850     9.356338   6.663829   0.659420  
3   9318.770758    94.029731   46.795674     9.782892   6.521667   0.710311  
4   9319.767442    91.346072   39.452248     7.465816   5.998869   0.595160  
5   9324.987387    93.456059   85.720950    71.502410   7.660249   4.372393  
6   9296.479949   103.101388   48.179711     9.284312   6.610490   0.643236  
7   9436.314482   582.406840   42.821190    11.388704   6.202694   0.914983  
8   9260.461750    98.969762   48.081932     9.301864   6.608451   0.651606  
9   9408.724773   107.757011   47.251733     9.141852   6.538405   0.645150  
10  9394.109790   731.657661   47.313074    10.558246   6.544557   0.758445  
11  9286.802519    92.753427   28.318999    12.675905   4.937949   1.309964  
12  9266.395417    95.791208   76.471174    40.937483   8.065845   2.154978  
13  9312.825440    98.886985   48.623762     7.744387   6.652908   0.529044  
14  9246.733555    90.895708   33.533035    10.216814   5.496946   0.837846  
15  9262.405750    95.058946   46.051072     7.688633   6.479283   0.545294  
16  9444.825502   103.400938   47.939331     7.412596   6.598831   0.520768  
17  9246.788588    92.058758   38.631544     8.504374   5.926439   0.661216  
18  9248.932165    89.742005   34.705196     7.130745   5.626404   0.576027  
19  9252.414339    91.421921  124.475967    64.987460  10.054414   3.403133  
20  9233.895799   101.831369   48.333624     8.632912   6.627846   0.588131  
21  9205.112